import React, { useEffect, useState } from "react";
import { toast } from "react-toastify";

import api from "../../api/api";


const AdminHome = () => {
    const [intro, setIntro] = useState({ title: "", subtitle: "" });
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [generating, setGenerating] = useState(false);

    const fetchHomeData = async () => {
        try {
            setLoading(true);
            const res = await api.get("/home");
            if (res.data?.intro) setIntro(res.data.intro);
        } catch {
            toast.error("Failed to load home data");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchHomeData();
    }, []);

    const generateIntro = async () => {
        try {
            setGenerating(true);
            const res = await api.post("/home/generate-intro", {
                businessName: intro.title || "Service Hub",
                focus: intro.subtitle || "electronics and digital media",
            });

            if (res.data?.intro) {
                setIntro(res.data.intro);
                toast.success("Intro generated by AI");
            } else {
                toast.error("AI did not return intro text");
            }
        } catch (err) {
            console.error(err);
            toast.error("Failed to generate with AI");
        } finally {
            setGenerating(false);
        }
    };

    const saveIntro = async () => {
        try {
            setSaving(true);
            await api.put("/home", { intro });
            toast.success("Intro section updated successfully!");
        } catch (err) {
            console.error(err);
            toast.error("Failed to update intro section");
        } finally {
            setSaving(false);
        }
    };

    if (loading) {
        return (
            <div className="fixed inset-0 flex items-center justify-center bg-gray-900 z-50">
                <div className="h-12 w-12 border-4 border-purple-500 border-t-transparent rounded-full animate-spin" />
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-900 text-gray-200 p-8 flex items-center justify-center">
            <div className="w-full max-w-3xl">
                <h2 className="text-2xl font-semibold mb-6">Manage Home Page</h2>

                {/* Intro Section */}
                <div className="bg-gray-800 rounded-xl p-6 mb-6">
                <h3 className="text-xl font-semibold mb-4">Intro Section</h3>
                <div className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">Title</label>
                        <input
                            type="text"
                            value={intro.title}
                            onChange={(e) => setIntro({ ...intro, title: e.target.value })}
                            className="w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                            placeholder="Enter intro title"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">Subtitle</label>
                        <textarea
                            value={intro.subtitle}
                            onChange={(e) => setIntro({ ...intro, subtitle: e.target.value })}
                            rows={3}
                            className="w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                            placeholder="Enter intro subtitle"
                        />
                    </div>
                    <div className="flex justify-end gap-3">
                        <button
                            onClick={saveIntro}
                            disabled={saving || generating}
                            className="bg-purple-600 hover:bg-purple-700 text-white px-6 py-2 rounded-lg font-semibold transition disabled:opacity-50"
                        >
                            {saving ? "Saving..." : "Save Intro"}
                        </button>
                        <button
                            onClick={generateIntro}
                            disabled={generating || saving}
                            className="bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-2 rounded-lg font-semibold transition disabled:opacity-50"
                        >
                            {generating ? "Generating..." : "Generate by AI"}
                        </button>
                    </div>
                </div>
            </div>
            </div>
        </div>
    );
};


export default AdminHome;
